package buildcraftAdditions.client.models;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

import buildcraftAdditions.utils.RenderUtils;

/**
 * Copyright (c) 2014-2015, AEnterprise
 * http://buildcraftadditions.wordpress.com/
 * Eureka is distributed under the terms of GNU GPL v3.0
 * Please check the contents of the license located in
 * http://buildcraftadditions.wordpress.com/wiki/licensing-stuff/
 * <p/>
 * ModelBiped - Plenituz
 * Created using Tabula 4.1.1
 */
@SideOnly(Side.CLIENT)
public class BackPackModel extends ModelBiped {

	public static final BackPackModel INSTANCE = new BackPackModel();

	public ModelRenderer handleTopLeft;
	public ModelRenderer handleTopRight;
	public ModelRenderer shape11;
	public ModelRenderer shape11_1;
	public ModelRenderer shape11_2;
	public ModelRenderer shape11_3;
	public ModelRenderer shape11_4;
	public ModelRenderer shape11_5;
	public ModelRenderer shape11_6;
	public ModelRenderer shape11_7;
	public ModelRenderer shape11_8;
	public ModelRenderer shape11_9;
	public ModelRenderer shape21;
	public ModelRenderer shape22;
	public ModelRenderer shape22_1;
	public ModelRenderer shape25;
	public ModelRenderer shape38;
	public ModelRenderer shape38_1;
	public ModelRenderer shape38_2;
	public ModelRenderer shape38_3;
	public ModelRenderer shape38_4;
	public ModelRenderer shape38_5;
	public ModelRenderer shape38_6;
	public ModelRenderer shape21_1;
	public ModelRenderer shape21_2;
	public ModelRenderer shape21_3;
	public ModelRenderer shape21_4;
	public ModelRenderer shape49;
	public ModelRenderer shape49_1;
	public ModelRenderer shape49_2;
	public ModelRenderer capsuleCoreVert;
	public ModelRenderer capsuleThingy1;
	public ModelRenderer capsuleThingy2;
	public ModelRenderer capsuleThingy3;
	public ModelRenderer capsuleThingy4;
	public ModelRenderer capsuleCoreHori;
	public ModelRenderer capsuleCoreBR;
	public ModelRenderer capsuleCoreBL;
	public ModelRenderer capsuleCoreTL;
	public ModelRenderer capsuleCoreTR;
	public ModelRenderer capsuleCoreVert_1;
	public ModelRenderer capsuleThingy1_1;
	public ModelRenderer capsuleThingy2_1;
	public ModelRenderer capsuleThingy3_1;
	public ModelRenderer capsuleThingy4_1;
	public ModelRenderer capsuleCoreHori_1;
	public ModelRenderer capsuleCoreBR_1;
	public ModelRenderer capsuleCoreBL_1;
	public ModelRenderer capsuleCoreTL_1;
	public ModelRenderer capsuleCoreTR_1;
	public ModelRenderer capsuleCoreVert_2;
	public ModelRenderer capsuleThingy1_2;
	public ModelRenderer capsuleThingy2_2;
	public ModelRenderer capsuleThingy3_2;
	public ModelRenderer capsuleThingy4_2;
	public ModelRenderer capsuleCoreHori_2;
	public ModelRenderer capsuleCoreBR_2;
	public ModelRenderer capsuleCoreBL_2;
	public ModelRenderer capsuleCoreTL_2;
	public ModelRenderer capsuleCoreTR_2;
	public ModelRenderer capsuleCoreVert_3;
	public ModelRenderer capsuleThingy1_3;
	public ModelRenderer capsuleThingy2_3;
	public ModelRenderer capsuleThingy3_3;
	public ModelRenderer capsuleThingy4_3;
	public ModelRenderer capsuleCoreHori_3;
	public ModelRenderer capsuleCoreBR_3;
	public ModelRenderer capsuleCoreBL_3;
	public ModelRenderer capsuleCoreTL_3;
	public ModelRenderer capsuleCoreTR_3;

	private BackPackModel() {
		this.textureWidth = 128;
		this.textureHeight = 64;
		this.capsuleCoreBR = new ModelRenderer(this, 29, 21);
		this.capsuleCoreBR.setRotationPoint(1.0F, 2.5F, 4.7F);
		this.capsuleCoreBR.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape49_2 = new ModelRenderer(this, 59, 13);
		this.shape49_2.setRotationPoint(-1.5F, 8.6F, 3.0F);
		this.shape49_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy2_1 = new ModelRenderer(this, 46, 18);
		this.capsuleThingy2_1.setRotationPoint(1.3F, 4.3F, 5.7F);
		this.capsuleThingy2_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy3_2 = new ModelRenderer(this, 46, 18);
		this.capsuleThingy3_2.setRotationPoint(-1.7F, 5.3F, 5.7F);
		this.capsuleThingy3_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy4_3 = new ModelRenderer(this, 41, 18);
		this.capsuleThingy4_3.setRotationPoint(-2.5F, 2.1F, 5.7F);
		this.capsuleThingy4_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreBL_1 = new ModelRenderer(this, 29, 18);
		this.capsuleCoreBL_1.setRotationPoint(2.55F, 5.5F, 4.7F);
		this.capsuleCoreBL_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy4_2 = new ModelRenderer(this, 41, 18);
		this.capsuleThingy4_2.setRotationPoint(-2.5F, 5.1F, 5.7F);
		this.capsuleThingy4_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy2_3 = new ModelRenderer(this, 46, 18);
		this.capsuleThingy2_3.setRotationPoint(-2.7F, 1.3F, 5.7F);
		this.capsuleThingy2_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape11_7 = new ModelRenderer(this, 0, 0);
		this.shape11_7.setRotationPoint(3.0F, 1.0F, -3.0F);
		this.shape11_7.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreBR_2 = new ModelRenderer(this, 29, 21);
		this.capsuleCoreBR_2.setRotationPoint(-3.0F, 5.5F, 4.7F);
		this.capsuleCoreBR_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreHori_1 = new ModelRenderer(this, 22, 16);
		this.capsuleCoreHori_1.setRotationPoint(1.0F, 4.0F, 4.7F);
		this.capsuleCoreHori_1.addBox(0.0F, 0.7F, 0.0F, 2, 2, 1, 0.0F);
		this.capsuleCoreVert_1 = new ModelRenderer(this, 22, 20);
		this.capsuleCoreVert_1.setRotationPoint(1.0F, 4.0F, 4.7F);
		this.capsuleCoreVert_1.addBox(0.7F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
		this.capsuleThingy4_1 = new ModelRenderer(this, 41, 18);
		this.capsuleThingy4_1.setRotationPoint(1.5F, 5.1F, 5.7F);
		this.capsuleThingy4_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreTL_2 = new ModelRenderer(this, 35, 21);
		this.capsuleCoreTL_2.setRotationPoint(-1.45F, 4.0F, 4.7F);
		this.capsuleCoreTL_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy3_3 = new ModelRenderer(this, 46, 18);
		this.capsuleThingy3_3.setRotationPoint(-1.7F, 2.3F, 5.7F);
		this.capsuleThingy3_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape11_1 = new ModelRenderer(this, 0, 2);
		this.shape11_1.setRotationPoint(0.0F, 2.0F, -3.0F);
		this.shape11_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreHori_3 = new ModelRenderer(this, 22, 16);
		this.capsuleCoreHori_3.setRotationPoint(-3.0F, 1.0F, 4.7F);
		this.capsuleCoreHori_3.addBox(0.0F, 0.7F, 0.0F, 2, 2, 1, 0.0F);
		this.handleTopRight = new ModelRenderer(this, 71, 0);
		this.handleTopRight.setRotationPoint(-5.0F, -1.0F, -3.0F);
		this.handleTopRight.addBox(0.0F, 0.0F, 0.0F, 1, 1, 6, 0.0F);
		this.shape38_6 = new ModelRenderer(this, 0, 29);
		this.shape38_6.setRotationPoint(1.0F, 4.0F, 4.0F);
		this.shape38_6.addBox(0.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
		this.setRotateAngle(shape38_6, 0.0F, 0.0F, 1.5707963267948966F);
		this.handleTopLeft = new ModelRenderer(this, 86, 0);
		this.handleTopLeft.setRotationPoint(4.0F, -1.0F, -3.0F);
		this.handleTopLeft.addBox(0.0F, 0.0F, 0.0F, 1, 1, 6, 0.0F);
		this.shape49_1 = new ModelRenderer(this, 56, 15);
		this.shape49_1.setRotationPoint(-0.6F, 8.8F, 3.0F);
		this.shape49_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy1_1 = new ModelRenderer(this, 41, 18);
		this.capsuleThingy1_1.setRotationPoint(2.1F, 4.5F, 5.7F);
		this.capsuleThingy1_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreVert_3 = new ModelRenderer(this, 22, 20);
		this.capsuleCoreVert_3.setRotationPoint(-3.0F, 1.0F, 4.7F);
		this.capsuleCoreVert_3.addBox(0.7F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
		this.shape11 = new ModelRenderer(this, 0, 2);
		this.shape11.setRotationPoint(-1.0F, 2.0F, -3.0F);
		this.shape11.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape11_4 = new ModelRenderer(this, 0, 0);
		this.shape11_4.setRotationPoint(-3.0F, 1.0F, -3.0F);
		this.shape11_4.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape11_8 = new ModelRenderer(this, 0, 0);
		this.shape11_8.setRotationPoint(2.0F, 1.0F, -3.0F);
		this.shape11_8.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy3_1 = new ModelRenderer(this, 46, 18);
		this.capsuleThingy3_1.setRotationPoint(2.3F, 5.3F, 5.7F);
		this.capsuleThingy3_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape38_4 = new ModelRenderer(this, 0, 22);
		this.shape38_4.setRotationPoint(1.0F, 1.0F, 4.0F);
		this.shape38_4.addBox(0.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
		this.setRotateAngle(shape38_4, 0.0F, 0.0F, 1.5707963267948966F);
		this.capsuleThingy1_3 = new ModelRenderer(this, 41, 18);
		this.capsuleThingy1_3.setRotationPoint(-1.9F, 1.5F, 5.7F);
		this.capsuleThingy1_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreBR_1 = new ModelRenderer(this, 29, 21);
		this.capsuleCoreBR_1.setRotationPoint(1.0F, 5.5F, 4.7F);
		this.capsuleCoreBR_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreBL = new ModelRenderer(this, 29, 18);
		this.capsuleCoreBL.setRotationPoint(2.55F, 2.5F, 4.7F);
		this.capsuleCoreBL.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy2_2 = new ModelRenderer(this, 46, 18);
		this.capsuleThingy2_2.setRotationPoint(-2.7F, 4.3F, 5.7F);
		this.capsuleThingy2_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreTR_3 = new ModelRenderer(this, 35, 18);
		this.capsuleCoreTR_3.setRotationPoint(-3.0F, 1.0F, 4.7F);
		this.capsuleCoreTR_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy4 = new ModelRenderer(this, 41, 18);
		this.capsuleThingy4.setRotationPoint(1.5F, 2.1F, 5.7F);
		this.capsuleThingy4.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape38_1 = new ModelRenderer(this, 0, 19);
		this.shape38_1.setRotationPoint(-3.0F, 1.0F, 4.0F);
		this.shape38_1.addBox(0.0F, 0.0F, 0.0F, 5, 1, 1, 0.0F);
		this.setRotateAngle(shape38_1, 0.0F, 0.0F, 1.5707963267948966F);
		this.capsuleCoreHori_2 = new ModelRenderer(this, 22, 16);
		this.capsuleCoreHori_2.setRotationPoint(-3.0F, 4.0F, 4.7F);
		this.capsuleCoreHori_2.addBox(0.0F, 0.7F, 0.0F, 2, 2, 1, 0.0F);
		this.capsuleCoreBL_2 = new ModelRenderer(this, 29, 18);
		this.capsuleCoreBL_2.setRotationPoint(-1.45F, 5.5F, 4.7F);
		this.capsuleCoreBL_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape21 = new ModelRenderer(this, 22, 0);
		this.shape21.setRotationPoint(-5.0F, 0.0F, 2.0F);
		this.shape21.addBox(0.0F, 0.0F, 0.0F, 10, 7, 1, 0.0F);
		this.shape11_3 = new ModelRenderer(this, 0, 0);
		this.shape11_3.setRotationPoint(-4.0F, 1.0F, -3.0F);
		this.shape11_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape38_3 = new ModelRenderer(this, 0, 16);
		this.shape38_3.setRotationPoint(4.0F, 1.0F, 4.0F);
		this.shape38_3.addBox(0.0F, 0.0F, 0.0F, 5, 1, 1, 0.0F);
		this.setRotateAngle(shape38_3, 0.0F, 0.0F, 1.5707963267948966F);
		this.capsuleCoreBR_3 = new ModelRenderer(this, 29, 21);
		this.capsuleCoreBR_3.setRotationPoint(-3.0F, 2.5F, 4.7F);
		this.capsuleCoreBR_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape11_9 = new ModelRenderer(this, 0, 0);
		this.shape11_9.setRotationPoint(1.0F, 2.0F, -3.0F);
		this.shape11_9.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape22_1 = new ModelRenderer(this, 22, 11);
		this.shape22_1.setRotationPoint(-3.0F, 9.0F, 2.0F);
		this.shape22_1.addBox(0.0F, 0.0F, 0.0F, 6, 1, 1, 0.0F);
		this.shape38_2 = new ModelRenderer(this, 0, 33);
		this.shape38_2.setRotationPoint(-3.6F, 6.0F, 4.0F);
		this.shape38_2.addBox(0.0F, 0.0F, 0.0F, 8, 1, 1, 0.0F);
		this.shape21_3 = new ModelRenderer(this, 44, 0);
		this.shape21_3.setRotationPoint(4.0F, 0.0F, 3.0F);
		this.shape21_3.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1, 0.0F);
		this.capsuleCoreVert = new ModelRenderer(this, 22, 20);
		this.capsuleCoreVert.setRotationPoint(1.0F, 1.0F, 4.7F);
		this.capsuleCoreVert.addBox(0.7F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
		this.capsuleCoreTR_2 = new ModelRenderer(this, 35, 18);
		this.capsuleCoreTR_2.setRotationPoint(-3.0F, 4.0F, 4.7F);
		this.capsuleCoreTR_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape38 = new ModelRenderer(this, 0, 13);
		this.shape38.setRotationPoint(-4.0F, 0.3F, 4.0F);
		this.shape38.addBox(0.0F, 0.0F, 0.0F, 8, 1, 1, 0.0F);
		this.shape11_5 = new ModelRenderer(this, 0, 0);
		this.shape11_5.setRotationPoint(-2.0F, 2.0F, -3.0F);
		this.shape11_5.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy1 = new ModelRenderer(this, 41, 18);
		this.capsuleThingy1.setRotationPoint(2.1F, 1.5F, 5.7F);
		this.capsuleThingy1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape38_5 = new ModelRenderer(this, 0, 26);
		this.shape38_5.setRotationPoint(-3.0F, 3.0F, 4.0F);
		this.shape38_5.addBox(0.0F, 0.0F, 0.0F, 6, 1, 1, 0.0F);
		this.shape49 = new ModelRenderer(this, 54, 12);
		this.shape49.setRotationPoint(0.4F, 8.6F, 3.0F);
		this.shape49.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape21_4 = new ModelRenderer(this, 49, 9);
		this.shape21_4.setRotationPoint(-3.6F, 7.0F, 3.0F);
		this.shape21_4.addBox(0.0F, 0.0F, 0.0F, 8, 1, 1, 0.0F);
		this.capsuleCoreHori = new ModelRenderer(this, 22, 16);
		this.capsuleCoreHori.setRotationPoint(1.0F, 1.0F, 4.7F);
		this.capsuleCoreHori.addBox(0.0F, 0.7F, 0.0F, 2, 2, 1, 0.0F);
		this.capsuleCoreTL = new ModelRenderer(this, 35, 21);
		this.capsuleCoreTL.setRotationPoint(2.55F, 1.0F, 4.7F);
		this.capsuleCoreTL.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape11_2 = new ModelRenderer(this, 0, 0);
		this.shape11_2.setRotationPoint(-5.0F, 0.0F, -3.0F);
		this.shape11_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape25 = new ModelRenderer(this, 0, 36);
		this.shape25.setRotationPoint(-3.0F, 7.0F, 4.0F);
		this.shape25.addBox(0.0F, 0.0F, 0.0F, 6, 1, 1, 0.0F);
		this.shape22 = new ModelRenderer(this, 22, 8);
		this.shape22.setRotationPoint(-4.0F, 7.0F, 2.0F);
		this.shape22.addBox(0.0F, 0.0F, 0.0F, 8, 2, 1, 0.0F);
		this.capsuleCoreTR = new ModelRenderer(this, 35, 18);
		this.capsuleCoreTR.setRotationPoint(1.0F, 1.0F, 4.7F);
		this.capsuleCoreTR.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy2 = new ModelRenderer(this, 46, 18);
		this.capsuleThingy2.setRotationPoint(1.3F, 1.3F, 5.7F);
		this.capsuleThingy2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape21_2 = new ModelRenderer(this, 48, 0);
		this.shape21_2.setRotationPoint(-4.0F, 0.0F, 3.0F);
		this.shape21_2.addBox(0.0F, 0.0F, 0.0F, 8, 7, 1, 0.0F);
		this.capsuleCoreTL_1 = new ModelRenderer(this, 35, 21);
		this.capsuleCoreTL_1.setRotationPoint(2.55F, 4.0F, 4.7F);
		this.capsuleCoreTL_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreTR_1 = new ModelRenderer(this, 35, 18);
		this.capsuleCoreTR_1.setRotationPoint(1.0F, 4.0F, 4.7F);
		this.capsuleCoreTR_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleThingy1_2 = new ModelRenderer(this, 41, 18);
		this.capsuleThingy1_2.setRotationPoint(-1.9F, 4.5F, 5.7F);
		this.capsuleThingy1_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape21_1 = new ModelRenderer(this, 67, 0);
		this.shape21_1.setRotationPoint(-4.7F, 0.0F, 3.0F);
		this.shape21_1.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1, 0.0F);
		this.capsuleThingy3 = new ModelRenderer(this, 46, 18);
		this.capsuleThingy3.setRotationPoint(2.3F, 2.3F, 5.7F);
		this.capsuleThingy3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreVert_2 = new ModelRenderer(this, 22, 20);
		this.capsuleCoreVert_2.setRotationPoint(-3.0F, 4.0F, 4.7F);
		this.capsuleCoreVert_2.addBox(0.7F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
		this.capsuleCoreTL_3 = new ModelRenderer(this, 35, 21);
		this.capsuleCoreTL_3.setRotationPoint(-1.45F, 1.0F, 4.7F);
		this.capsuleCoreTL_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.capsuleCoreBL_3 = new ModelRenderer(this, 29, 18);
		this.capsuleCoreBL_3.setRotationPoint(-1.45F, 2.5F, 4.7F);
		this.capsuleCoreBL_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
		this.shape11_6 = new ModelRenderer(this, 0, 0);
		this.shape11_6.setRotationPoint(4.0F, 0.0F, -3.0F);
		this.shape11_6.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		RenderUtils.bindTexture(new ResourceLocation("bcadditions", "textures/models/armor/kineticBackpack_layer_1.png"));
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreBR.offsetX, this.capsuleCoreBR.offsetY, this.capsuleCoreBR.offsetZ);
		GL11.glTranslatef(this.capsuleCoreBR.rotationPointX * f5, this.capsuleCoreBR.rotationPointY * f5, this.capsuleCoreBR.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreBR.offsetX, -this.capsuleCoreBR.offsetY, -this.capsuleCoreBR.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreBR.rotationPointX * f5, -this.capsuleCoreBR.rotationPointY * f5, -this.capsuleCoreBR.rotationPointZ * f5);
		this.capsuleCoreBR.render(f5);
		GL11.glPopMatrix();
		this.shape49_2.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy2_1.offsetX, this.capsuleThingy2_1.offsetY, this.capsuleThingy2_1.offsetZ);
		GL11.glTranslatef(this.capsuleThingy2_1.rotationPointX * f5, this.capsuleThingy2_1.rotationPointY * f5, this.capsuleThingy2_1.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy2_1.offsetX, -this.capsuleThingy2_1.offsetY, -this.capsuleThingy2_1.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy2_1.rotationPointX * f5, -this.capsuleThingy2_1.rotationPointY * f5, -this.capsuleThingy2_1.rotationPointZ * f5);
		this.capsuleThingy2_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy3_2.offsetX, this.capsuleThingy3_2.offsetY, this.capsuleThingy3_2.offsetZ);
		GL11.glTranslatef(this.capsuleThingy3_2.rotationPointX * f5, this.capsuleThingy3_2.rotationPointY * f5, this.capsuleThingy3_2.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy3_2.offsetX, -this.capsuleThingy3_2.offsetY, -this.capsuleThingy3_2.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy3_2.rotationPointX * f5, -this.capsuleThingy3_2.rotationPointY * f5, -this.capsuleThingy3_2.rotationPointZ * f5);
		this.capsuleThingy3_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy4_3.offsetX, this.capsuleThingy4_3.offsetY, this.capsuleThingy4_3.offsetZ);
		GL11.glTranslatef(this.capsuleThingy4_3.rotationPointX * f5, this.capsuleThingy4_3.rotationPointY * f5, this.capsuleThingy4_3.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy4_3.offsetX, -this.capsuleThingy4_3.offsetY, -this.capsuleThingy4_3.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy4_3.rotationPointX * f5, -this.capsuleThingy4_3.rotationPointY * f5, -this.capsuleThingy4_3.rotationPointZ * f5);
		this.capsuleThingy4_3.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreBL_1.offsetX, this.capsuleCoreBL_1.offsetY, this.capsuleCoreBL_1.offsetZ);
		GL11.glTranslatef(this.capsuleCoreBL_1.rotationPointX * f5, this.capsuleCoreBL_1.rotationPointY * f5, this.capsuleCoreBL_1.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreBL_1.offsetX, -this.capsuleCoreBL_1.offsetY, -this.capsuleCoreBL_1.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreBL_1.rotationPointX * f5, -this.capsuleCoreBL_1.rotationPointY * f5, -this.capsuleCoreBL_1.rotationPointZ * f5);
		this.capsuleCoreBL_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy4_2.offsetX, this.capsuleThingy4_2.offsetY, this.capsuleThingy4_2.offsetZ);
		GL11.glTranslatef(this.capsuleThingy4_2.rotationPointX * f5, this.capsuleThingy4_2.rotationPointY * f5, this.capsuleThingy4_2.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy4_2.offsetX, -this.capsuleThingy4_2.offsetY, -this.capsuleThingy4_2.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy4_2.rotationPointX * f5, -this.capsuleThingy4_2.rotationPointY * f5, -this.capsuleThingy4_2.rotationPointZ * f5);
		this.capsuleThingy4_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy2_3.offsetX, this.capsuleThingy2_3.offsetY, this.capsuleThingy2_3.offsetZ);
		GL11.glTranslatef(this.capsuleThingy2_3.rotationPointX * f5, this.capsuleThingy2_3.rotationPointY * f5, this.capsuleThingy2_3.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy2_3.offsetX, -this.capsuleThingy2_3.offsetY, -this.capsuleThingy2_3.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy2_3.rotationPointX * f5, -this.capsuleThingy2_3.rotationPointY * f5, -this.capsuleThingy2_3.rotationPointZ * f5);
		this.capsuleThingy2_3.render(f5);
		GL11.glPopMatrix();
		this.shape11_7.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreBR_2.offsetX, this.capsuleCoreBR_2.offsetY, this.capsuleCoreBR_2.offsetZ);
		GL11.glTranslatef(this.capsuleCoreBR_2.rotationPointX * f5, this.capsuleCoreBR_2.rotationPointY * f5, this.capsuleCoreBR_2.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreBR_2.offsetX, -this.capsuleCoreBR_2.offsetY, -this.capsuleCoreBR_2.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreBR_2.rotationPointX * f5, -this.capsuleCoreBR_2.rotationPointY * f5, -this.capsuleCoreBR_2.rotationPointZ * f5);
		this.capsuleCoreBR_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreHori_1.offsetX, this.capsuleCoreHori_1.offsetY, this.capsuleCoreHori_1.offsetZ);
		GL11.glTranslatef(this.capsuleCoreHori_1.rotationPointX * f5, this.capsuleCoreHori_1.rotationPointY * f5, this.capsuleCoreHori_1.rotationPointZ * f5);
		GL11.glScaled(1.0D, 0.6D, 1.0D);
		GL11.glTranslatef(-this.capsuleCoreHori_1.offsetX, -this.capsuleCoreHori_1.offsetY, -this.capsuleCoreHori_1.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreHori_1.rotationPointX * f5, -this.capsuleCoreHori_1.rotationPointY * f5, -this.capsuleCoreHori_1.rotationPointZ * f5);
		this.capsuleCoreHori_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreVert_1.offsetX, this.capsuleCoreVert_1.offsetY, this.capsuleCoreVert_1.offsetZ);
		GL11.glTranslatef(this.capsuleCoreVert_1.rotationPointX * f5, this.capsuleCoreVert_1.rotationPointY * f5, this.capsuleCoreVert_1.rotationPointZ * f5);
		GL11.glScaled(0.6D, 1.0D, 1.0D);
		GL11.glTranslatef(-this.capsuleCoreVert_1.offsetX, -this.capsuleCoreVert_1.offsetY, -this.capsuleCoreVert_1.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreVert_1.rotationPointX * f5, -this.capsuleCoreVert_1.rotationPointY * f5, -this.capsuleCoreVert_1.rotationPointZ * f5);
		this.capsuleCoreVert_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy4_1.offsetX, this.capsuleThingy4_1.offsetY, this.capsuleThingy4_1.offsetZ);
		GL11.glTranslatef(this.capsuleThingy4_1.rotationPointX * f5, this.capsuleThingy4_1.rotationPointY * f5, this.capsuleThingy4_1.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy4_1.offsetX, -this.capsuleThingy4_1.offsetY, -this.capsuleThingy4_1.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy4_1.rotationPointX * f5, -this.capsuleThingy4_1.rotationPointY * f5, -this.capsuleThingy4_1.rotationPointZ * f5);
		this.capsuleThingy4_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreTL_2.offsetX, this.capsuleCoreTL_2.offsetY, this.capsuleCoreTL_2.offsetZ);
		GL11.glTranslatef(this.capsuleCoreTL_2.rotationPointX * f5, this.capsuleCoreTL_2.rotationPointY * f5, this.capsuleCoreTL_2.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreTL_2.offsetX, -this.capsuleCoreTL_2.offsetY, -this.capsuleCoreTL_2.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreTL_2.rotationPointX * f5, -this.capsuleCoreTL_2.rotationPointY * f5, -this.capsuleCoreTL_2.rotationPointZ * f5);
		this.capsuleCoreTL_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy3_3.offsetX, this.capsuleThingy3_3.offsetY, this.capsuleThingy3_3.offsetZ);
		GL11.glTranslatef(this.capsuleThingy3_3.rotationPointX * f5, this.capsuleThingy3_3.rotationPointY * f5, this.capsuleThingy3_3.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy3_3.offsetX, -this.capsuleThingy3_3.offsetY, -this.capsuleThingy3_3.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy3_3.rotationPointX * f5, -this.capsuleThingy3_3.rotationPointY * f5, -this.capsuleThingy3_3.rotationPointZ * f5);
		this.capsuleThingy3_3.render(f5);
		GL11.glPopMatrix();
		this.shape11_1.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreHori_3.offsetX, this.capsuleCoreHori_3.offsetY, this.capsuleCoreHori_3.offsetZ);
		GL11.glTranslatef(this.capsuleCoreHori_3.rotationPointX * f5, this.capsuleCoreHori_3.rotationPointY * f5, this.capsuleCoreHori_3.rotationPointZ * f5);
		GL11.glScaled(1.0D, 0.6D, 1.0D);
		GL11.glTranslatef(-this.capsuleCoreHori_3.offsetX, -this.capsuleCoreHori_3.offsetY, -this.capsuleCoreHori_3.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreHori_3.rotationPointX * f5, -this.capsuleCoreHori_3.rotationPointY * f5, -this.capsuleCoreHori_3.rotationPointZ * f5);
		this.capsuleCoreHori_3.render(f5);
		GL11.glPopMatrix();
		this.handleTopRight.render(f5);
		this.shape38_6.render(f5);
		this.handleTopLeft.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.shape49_1.offsetX, this.shape49_1.offsetY, this.shape49_1.offsetZ);
		GL11.glTranslatef(this.shape49_1.rotationPointX * f5, this.shape49_1.rotationPointY * f5, this.shape49_1.rotationPointZ * f5);
		GL11.glScaled(1.0D, 0.6D, 1.0D);
		GL11.glTranslatef(-this.shape49_1.offsetX, -this.shape49_1.offsetY, -this.shape49_1.offsetZ);
		GL11.glTranslatef(-this.shape49_1.rotationPointX * f5, -this.shape49_1.rotationPointY * f5, -this.shape49_1.rotationPointZ * f5);
		this.shape49_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy1_1.offsetX, this.capsuleThingy1_1.offsetY, this.capsuleThingy1_1.offsetZ);
		GL11.glTranslatef(this.capsuleThingy1_1.rotationPointX * f5, this.capsuleThingy1_1.rotationPointY * f5, this.capsuleThingy1_1.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy1_1.offsetX, -this.capsuleThingy1_1.offsetY, -this.capsuleThingy1_1.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy1_1.rotationPointX * f5, -this.capsuleThingy1_1.rotationPointY * f5, -this.capsuleThingy1_1.rotationPointZ * f5);
		this.capsuleThingy1_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreVert_3.offsetX, this.capsuleCoreVert_3.offsetY, this.capsuleCoreVert_3.offsetZ);
		GL11.glTranslatef(this.capsuleCoreVert_3.rotationPointX * f5, this.capsuleCoreVert_3.rotationPointY * f5, this.capsuleCoreVert_3.rotationPointZ * f5);
		GL11.glScaled(0.6D, 1.0D, 1.0D);
		GL11.glTranslatef(-this.capsuleCoreVert_3.offsetX, -this.capsuleCoreVert_3.offsetY, -this.capsuleCoreVert_3.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreVert_3.rotationPointX * f5, -this.capsuleCoreVert_3.rotationPointY * f5, -this.capsuleCoreVert_3.rotationPointZ * f5);
		this.capsuleCoreVert_3.render(f5);
		GL11.glPopMatrix();
		this.shape11.render(f5);
		this.shape11_4.render(f5);
		this.shape11_8.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy3_1.offsetX, this.capsuleThingy3_1.offsetY, this.capsuleThingy3_1.offsetZ);
		GL11.glTranslatef(this.capsuleThingy3_1.rotationPointX * f5, this.capsuleThingy3_1.rotationPointY * f5, this.capsuleThingy3_1.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy3_1.offsetX, -this.capsuleThingy3_1.offsetY, -this.capsuleThingy3_1.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy3_1.rotationPointX * f5, -this.capsuleThingy3_1.rotationPointY * f5, -this.capsuleThingy3_1.rotationPointZ * f5);
		this.capsuleThingy3_1.render(f5);
		GL11.glPopMatrix();
		this.shape38_4.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy1_3.offsetX, this.capsuleThingy1_3.offsetY, this.capsuleThingy1_3.offsetZ);
		GL11.glTranslatef(this.capsuleThingy1_3.rotationPointX * f5, this.capsuleThingy1_3.rotationPointY * f5, this.capsuleThingy1_3.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy1_3.offsetX, -this.capsuleThingy1_3.offsetY, -this.capsuleThingy1_3.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy1_3.rotationPointX * f5, -this.capsuleThingy1_3.rotationPointY * f5, -this.capsuleThingy1_3.rotationPointZ * f5);
		this.capsuleThingy1_3.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreBR_1.offsetX, this.capsuleCoreBR_1.offsetY, this.capsuleCoreBR_1.offsetZ);
		GL11.glTranslatef(this.capsuleCoreBR_1.rotationPointX * f5, this.capsuleCoreBR_1.rotationPointY * f5, this.capsuleCoreBR_1.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreBR_1.offsetX, -this.capsuleCoreBR_1.offsetY, -this.capsuleCoreBR_1.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreBR_1.rotationPointX * f5, -this.capsuleCoreBR_1.rotationPointY * f5, -this.capsuleCoreBR_1.rotationPointZ * f5);
		this.capsuleCoreBR_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreBL.offsetX, this.capsuleCoreBL.offsetY, this.capsuleCoreBL.offsetZ);
		GL11.glTranslatef(this.capsuleCoreBL.rotationPointX * f5, this.capsuleCoreBL.rotationPointY * f5, this.capsuleCoreBL.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreBL.offsetX, -this.capsuleCoreBL.offsetY, -this.capsuleCoreBL.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreBL.rotationPointX * f5, -this.capsuleCoreBL.rotationPointY * f5, -this.capsuleCoreBL.rotationPointZ * f5);
		this.capsuleCoreBL.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy2_2.offsetX, this.capsuleThingy2_2.offsetY, this.capsuleThingy2_2.offsetZ);
		GL11.glTranslatef(this.capsuleThingy2_2.rotationPointX * f5, this.capsuleThingy2_2.rotationPointY * f5, this.capsuleThingy2_2.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy2_2.offsetX, -this.capsuleThingy2_2.offsetY, -this.capsuleThingy2_2.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy2_2.rotationPointX * f5, -this.capsuleThingy2_2.rotationPointY * f5, -this.capsuleThingy2_2.rotationPointZ * f5);
		this.capsuleThingy2_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreTR_3.offsetX, this.capsuleCoreTR_3.offsetY, this.capsuleCoreTR_3.offsetZ);
		GL11.glTranslatef(this.capsuleCoreTR_3.rotationPointX * f5, this.capsuleCoreTR_3.rotationPointY * f5, this.capsuleCoreTR_3.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreTR_3.offsetX, -this.capsuleCoreTR_3.offsetY, -this.capsuleCoreTR_3.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreTR_3.rotationPointX * f5, -this.capsuleCoreTR_3.rotationPointY * f5, -this.capsuleCoreTR_3.rotationPointZ * f5);
		this.capsuleCoreTR_3.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy4.offsetX, this.capsuleThingy4.offsetY, this.capsuleThingy4.offsetZ);
		GL11.glTranslatef(this.capsuleThingy4.rotationPointX * f5, this.capsuleThingy4.rotationPointY * f5, this.capsuleThingy4.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy4.offsetX, -this.capsuleThingy4.offsetY, -this.capsuleThingy4.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy4.rotationPointX * f5, -this.capsuleThingy4.rotationPointY * f5, -this.capsuleThingy4.rotationPointZ * f5);
		this.capsuleThingy4.render(f5);
		GL11.glPopMatrix();
		this.shape38_1.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreHori_2.offsetX, this.capsuleCoreHori_2.offsetY, this.capsuleCoreHori_2.offsetZ);
		GL11.glTranslatef(this.capsuleCoreHori_2.rotationPointX * f5, this.capsuleCoreHori_2.rotationPointY * f5, this.capsuleCoreHori_2.rotationPointZ * f5);
		GL11.glScaled(1.0D, 0.6D, 1.0D);
		GL11.glTranslatef(-this.capsuleCoreHori_2.offsetX, -this.capsuleCoreHori_2.offsetY, -this.capsuleCoreHori_2.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreHori_2.rotationPointX * f5, -this.capsuleCoreHori_2.rotationPointY * f5, -this.capsuleCoreHori_2.rotationPointZ * f5);
		this.capsuleCoreHori_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreBL_2.offsetX, this.capsuleCoreBL_2.offsetY, this.capsuleCoreBL_2.offsetZ);
		GL11.glTranslatef(this.capsuleCoreBL_2.rotationPointX * f5, this.capsuleCoreBL_2.rotationPointY * f5, this.capsuleCoreBL_2.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreBL_2.offsetX, -this.capsuleCoreBL_2.offsetY, -this.capsuleCoreBL_2.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreBL_2.rotationPointX * f5, -this.capsuleCoreBL_2.rotationPointY * f5, -this.capsuleCoreBL_2.rotationPointZ * f5);
		this.capsuleCoreBL_2.render(f5);
		GL11.glPopMatrix();
		this.shape21.render(f5);
		this.shape11_3.render(f5);
		this.shape38_3.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreBR_3.offsetX, this.capsuleCoreBR_3.offsetY, this.capsuleCoreBR_3.offsetZ);
		GL11.glTranslatef(this.capsuleCoreBR_3.rotationPointX * f5, this.capsuleCoreBR_3.rotationPointY * f5, this.capsuleCoreBR_3.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreBR_3.offsetX, -this.capsuleCoreBR_3.offsetY, -this.capsuleCoreBR_3.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreBR_3.rotationPointX * f5, -this.capsuleCoreBR_3.rotationPointY * f5, -this.capsuleCoreBR_3.rotationPointZ * f5);
		this.capsuleCoreBR_3.render(f5);
		GL11.glPopMatrix();
		this.shape11_9.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.shape22_1.offsetX, this.shape22_1.offsetY, this.shape22_1.offsetZ);
		GL11.glTranslatef(this.shape22_1.rotationPointX * f5, this.shape22_1.rotationPointY * f5, this.shape22_1.rotationPointZ * f5);
		GL11.glScaled(1.0D, 1.3D, 1.0D);
		GL11.glTranslatef(-this.shape22_1.offsetX, -this.shape22_1.offsetY, -this.shape22_1.offsetZ);
		GL11.glTranslatef(-this.shape22_1.rotationPointX * f5, -this.shape22_1.rotationPointY * f5, -this.shape22_1.rotationPointZ * f5);
		this.shape22_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.shape38_2.offsetX, this.shape38_2.offsetY, this.shape38_2.offsetZ);
		GL11.glTranslatef(this.shape38_2.rotationPointX * f5, this.shape38_2.rotationPointY * f5, this.shape38_2.rotationPointZ * f5);
		GL11.glScaled(0.9D, 1.0D, 1.0D);
		GL11.glTranslatef(-this.shape38_2.offsetX, -this.shape38_2.offsetY, -this.shape38_2.offsetZ);
		GL11.glTranslatef(-this.shape38_2.rotationPointX * f5, -this.shape38_2.rotationPointY * f5, -this.shape38_2.rotationPointZ * f5);
		this.shape38_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.shape21_3.offsetX, this.shape21_3.offsetY, this.shape21_3.offsetZ);
		GL11.glTranslatef(this.shape21_3.rotationPointX * f5, this.shape21_3.rotationPointY * f5, this.shape21_3.rotationPointZ * f5);
		GL11.glScaled(0.7D, 1.0D, 1.0D);
		GL11.glTranslatef(-this.shape21_3.offsetX, -this.shape21_3.offsetY, -this.shape21_3.offsetZ);
		GL11.glTranslatef(-this.shape21_3.rotationPointX * f5, -this.shape21_3.rotationPointY * f5, -this.shape21_3.rotationPointZ * f5);
		this.shape21_3.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreVert.offsetX, this.capsuleCoreVert.offsetY, this.capsuleCoreVert.offsetZ);
		GL11.glTranslatef(this.capsuleCoreVert.rotationPointX * f5, this.capsuleCoreVert.rotationPointY * f5, this.capsuleCoreVert.rotationPointZ * f5);
		GL11.glScaled(0.6D, 1.0D, 1.0D);
		GL11.glTranslatef(-this.capsuleCoreVert.offsetX, -this.capsuleCoreVert.offsetY, -this.capsuleCoreVert.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreVert.rotationPointX * f5, -this.capsuleCoreVert.rotationPointY * f5, -this.capsuleCoreVert.rotationPointZ * f5);
		this.capsuleCoreVert.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreTR_2.offsetX, this.capsuleCoreTR_2.offsetY, this.capsuleCoreTR_2.offsetZ);
		GL11.glTranslatef(this.capsuleCoreTR_2.rotationPointX * f5, this.capsuleCoreTR_2.rotationPointY * f5, this.capsuleCoreTR_2.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreTR_2.offsetX, -this.capsuleCoreTR_2.offsetY, -this.capsuleCoreTR_2.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreTR_2.rotationPointX * f5, -this.capsuleCoreTR_2.rotationPointY * f5, -this.capsuleCoreTR_2.rotationPointZ * f5);
		this.capsuleCoreTR_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.shape38.offsetX, this.shape38.offsetY, this.shape38.offsetZ);
		GL11.glTranslatef(this.shape38.rotationPointX * f5, this.shape38.rotationPointY * f5, this.shape38.rotationPointZ * f5);
		GL11.glScaled(1.0D, 0.7D, 1.0D);
		GL11.glTranslatef(-this.shape38.offsetX, -this.shape38.offsetY, -this.shape38.offsetZ);
		GL11.glTranslatef(-this.shape38.rotationPointX * f5, -this.shape38.rotationPointY * f5, -this.shape38.rotationPointZ * f5);
		this.shape38.render(f5);
		GL11.glPopMatrix();
		this.shape11_5.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy1.offsetX, this.capsuleThingy1.offsetY, this.capsuleThingy1.offsetZ);
		GL11.glTranslatef(this.capsuleThingy1.rotationPointX * f5, this.capsuleThingy1.rotationPointY * f5, this.capsuleThingy1.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy1.offsetX, -this.capsuleThingy1.offsetY, -this.capsuleThingy1.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy1.rotationPointX * f5, -this.capsuleThingy1.rotationPointY * f5, -this.capsuleThingy1.rotationPointZ * f5);
		this.capsuleThingy1.render(f5);
		GL11.glPopMatrix();
		this.shape38_5.render(f5);
		this.shape49.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.shape21_4.offsetX, this.shape21_4.offsetY, this.shape21_4.offsetZ);
		GL11.glTranslatef(this.shape21_4.rotationPointX * f5, this.shape21_4.rotationPointY * f5, this.shape21_4.rotationPointZ * f5);
		GL11.glScaled(0.9D, 1.0D, 1.0D);
		GL11.glTranslatef(-this.shape21_4.offsetX, -this.shape21_4.offsetY, -this.shape21_4.offsetZ);
		GL11.glTranslatef(-this.shape21_4.rotationPointX * f5, -this.shape21_4.rotationPointY * f5, -this.shape21_4.rotationPointZ * f5);
		this.shape21_4.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreHori.offsetX, this.capsuleCoreHori.offsetY, this.capsuleCoreHori.offsetZ);
		GL11.glTranslatef(this.capsuleCoreHori.rotationPointX * f5, this.capsuleCoreHori.rotationPointY * f5, this.capsuleCoreHori.rotationPointZ * f5);
		GL11.glScaled(1.0D, 0.6D, 1.0D);
		GL11.glTranslatef(-this.capsuleCoreHori.offsetX, -this.capsuleCoreHori.offsetY, -this.capsuleCoreHori.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreHori.rotationPointX * f5, -this.capsuleCoreHori.rotationPointY * f5, -this.capsuleCoreHori.rotationPointZ * f5);
		this.capsuleCoreHori.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreTL.offsetX, this.capsuleCoreTL.offsetY, this.capsuleCoreTL.offsetZ);
		GL11.glTranslatef(this.capsuleCoreTL.rotationPointX * f5, this.capsuleCoreTL.rotationPointY * f5, this.capsuleCoreTL.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreTL.offsetX, -this.capsuleCoreTL.offsetY, -this.capsuleCoreTL.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreTL.rotationPointX * f5, -this.capsuleCoreTL.rotationPointY * f5, -this.capsuleCoreTL.rotationPointZ * f5);
		this.capsuleCoreTL.render(f5);
		GL11.glPopMatrix();
		this.shape11_2.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.shape25.offsetX, this.shape25.offsetY, this.shape25.offsetZ);
		GL11.glTranslatef(this.shape25.rotationPointX * f5, this.shape25.rotationPointY * f5, this.shape25.rotationPointZ * f5);
		GL11.glScaled(1.0D, 0.7D, 1.0D);
		GL11.glTranslatef(-this.shape25.offsetX, -this.shape25.offsetY, -this.shape25.offsetZ);
		GL11.glTranslatef(-this.shape25.rotationPointX * f5, -this.shape25.rotationPointY * f5, -this.shape25.rotationPointZ * f5);
		this.shape25.render(f5);
		GL11.glPopMatrix();
		this.shape22.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreTR.offsetX, this.capsuleCoreTR.offsetY, this.capsuleCoreTR.offsetZ);
		GL11.glTranslatef(this.capsuleCoreTR.rotationPointX * f5, this.capsuleCoreTR.rotationPointY * f5, this.capsuleCoreTR.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreTR.offsetX, -this.capsuleCoreTR.offsetY, -this.capsuleCoreTR.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreTR.rotationPointX * f5, -this.capsuleCoreTR.rotationPointY * f5, -this.capsuleCoreTR.rotationPointZ * f5);
		this.capsuleCoreTR.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy2.offsetX, this.capsuleThingy2.offsetY, this.capsuleThingy2.offsetZ);
		GL11.glTranslatef(this.capsuleThingy2.rotationPointX * f5, this.capsuleThingy2.rotationPointY * f5, this.capsuleThingy2.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy2.offsetX, -this.capsuleThingy2.offsetY, -this.capsuleThingy2.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy2.rotationPointX * f5, -this.capsuleThingy2.rotationPointY * f5, -this.capsuleThingy2.rotationPointZ * f5);
		this.capsuleThingy2.render(f5);
		GL11.glPopMatrix();
		this.shape21_2.render(f5);
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreTL_1.offsetX, this.capsuleCoreTL_1.offsetY, this.capsuleCoreTL_1.offsetZ);
		GL11.glTranslatef(this.capsuleCoreTL_1.rotationPointX * f5, this.capsuleCoreTL_1.rotationPointY * f5, this.capsuleCoreTL_1.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreTL_1.offsetX, -this.capsuleCoreTL_1.offsetY, -this.capsuleCoreTL_1.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreTL_1.rotationPointX * f5, -this.capsuleCoreTL_1.rotationPointY * f5, -this.capsuleCoreTL_1.rotationPointZ * f5);
		this.capsuleCoreTL_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreTR_1.offsetX, this.capsuleCoreTR_1.offsetY, this.capsuleCoreTR_1.offsetZ);
		GL11.glTranslatef(this.capsuleCoreTR_1.rotationPointX * f5, this.capsuleCoreTR_1.rotationPointY * f5, this.capsuleCoreTR_1.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreTR_1.offsetX, -this.capsuleCoreTR_1.offsetY, -this.capsuleCoreTR_1.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreTR_1.rotationPointX * f5, -this.capsuleCoreTR_1.rotationPointY * f5, -this.capsuleCoreTR_1.rotationPointZ * f5);
		this.capsuleCoreTR_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy1_2.offsetX, this.capsuleThingy1_2.offsetY, this.capsuleThingy1_2.offsetZ);
		GL11.glTranslatef(this.capsuleThingy1_2.rotationPointX * f5, this.capsuleThingy1_2.rotationPointY * f5, this.capsuleThingy1_2.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy1_2.offsetX, -this.capsuleThingy1_2.offsetY, -this.capsuleThingy1_2.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy1_2.rotationPointX * f5, -this.capsuleThingy1_2.rotationPointY * f5, -this.capsuleThingy1_2.rotationPointZ * f5);
		this.capsuleThingy1_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.shape21_1.offsetX, this.shape21_1.offsetY, this.shape21_1.offsetZ);
		GL11.glTranslatef(this.shape21_1.rotationPointX * f5, this.shape21_1.rotationPointY * f5, this.shape21_1.rotationPointZ * f5);
		GL11.glScaled(0.7D, 1.0D, 1.0D);
		GL11.glTranslatef(-this.shape21_1.offsetX, -this.shape21_1.offsetY, -this.shape21_1.offsetZ);
		GL11.glTranslatef(-this.shape21_1.rotationPointX * f5, -this.shape21_1.rotationPointY * f5, -this.shape21_1.rotationPointZ * f5);
		this.shape21_1.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleThingy3.offsetX, this.capsuleThingy3.offsetY, this.capsuleThingy3.offsetZ);
		GL11.glTranslatef(this.capsuleThingy3.rotationPointX * f5, this.capsuleThingy3.rotationPointY * f5, this.capsuleThingy3.rotationPointZ * f5);
		GL11.glScaled(0.4D, 0.4D, 0.4D);
		GL11.glTranslatef(-this.capsuleThingy3.offsetX, -this.capsuleThingy3.offsetY, -this.capsuleThingy3.offsetZ);
		GL11.glTranslatef(-this.capsuleThingy3.rotationPointX * f5, -this.capsuleThingy3.rotationPointY * f5, -this.capsuleThingy3.rotationPointZ * f5);
		this.capsuleThingy3.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreVert_2.offsetX, this.capsuleCoreVert_2.offsetY, this.capsuleCoreVert_2.offsetZ);
		GL11.glTranslatef(this.capsuleCoreVert_2.rotationPointX * f5, this.capsuleCoreVert_2.rotationPointY * f5, this.capsuleCoreVert_2.rotationPointZ * f5);
		GL11.glScaled(0.6D, 1.0D, 1.0D);
		GL11.glTranslatef(-this.capsuleCoreVert_2.offsetX, -this.capsuleCoreVert_2.offsetY, -this.capsuleCoreVert_2.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreVert_2.rotationPointX * f5, -this.capsuleCoreVert_2.rotationPointY * f5, -this.capsuleCoreVert_2.rotationPointZ * f5);
		this.capsuleCoreVert_2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreTL_3.offsetX, this.capsuleCoreTL_3.offsetY, this.capsuleCoreTL_3.offsetZ);
		GL11.glTranslatef(this.capsuleCoreTL_3.rotationPointX * f5, this.capsuleCoreTL_3.rotationPointY * f5, this.capsuleCoreTL_3.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreTL_3.offsetX, -this.capsuleCoreTL_3.offsetY, -this.capsuleCoreTL_3.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreTL_3.rotationPointX * f5, -this.capsuleCoreTL_3.rotationPointY * f5, -this.capsuleCoreTL_3.rotationPointZ * f5);
		this.capsuleCoreTL_3.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glTranslatef(this.capsuleCoreBL_3.offsetX, this.capsuleCoreBL_3.offsetY, this.capsuleCoreBL_3.offsetZ);
		GL11.glTranslatef(this.capsuleCoreBL_3.rotationPointX * f5, this.capsuleCoreBL_3.rotationPointY * f5, this.capsuleCoreBL_3.rotationPointZ * f5);
		GL11.glScaled(0.45D, 0.5D, 0.5D);
		GL11.glTranslatef(-this.capsuleCoreBL_3.offsetX, -this.capsuleCoreBL_3.offsetY, -this.capsuleCoreBL_3.offsetZ);
		GL11.glTranslatef(-this.capsuleCoreBL_3.rotationPointX * f5, -this.capsuleCoreBL_3.rotationPointY * f5, -this.capsuleCoreBL_3.rotationPointZ * f5);
		this.capsuleCoreBL_3.render(f5);
		GL11.glPopMatrix();
		this.shape11_6.render(f5);

	}

	/**
	 * This is a helper function from Tabula to set the rotation of model parts
	 */
	public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
		modelRenderer.rotateAngleX = x;
		modelRenderer.rotateAngleY = y;
		modelRenderer.rotateAngleZ = z;
	}
}
